FROM node:14.15.1-alpine

RUN mkdir -p /home/app/code && mkdir -p /home/app/shared && chown -R node:node /home/app

WORKDIR /home/app/code

COPY frontend/package.json .

COPY frontend/yarn.lock .

RUN yarn install

COPY shared ../shared

USER node

COPY --chown=node:node frontend .

EXPOSE 3000
CMD [ "yarn", "dev" ]