FROM node:14.15.1-alpine

RUN mkdir -p /home/app/shopping-front && mkdir -p /home/app/shared && chown -R node:node /home/app

WORKDIR /home/app

COPY frontend/package.json ./shopping-front

COPY frontend/yarn.lock ./shopping-front

COPY shared ./shared


WORKDIR /home/app/shopping-front

RUN yarn install

USER node

COPY --chown=node:node frontend .

EXPOSE 5000
CMD [ "yarn", "dev" ]
