version: "3"
services:
  shopping-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/home/app/code
      - ./shared:/home/app/shared
    depends_on:
      - shopping-db

  shopping-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/app/code
      - ./shared:/home/app/shared

  shopping-db:
    image: postgres
    env_file:
      - ./.env.dev
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbvolume-dev:/var/lib/postgresql/data

  shopping-pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.dev
    ports:
      - "5433:80"
    volumes:
      - pgadminvolume-dev:/var/lib/pgadmin

volumes:
  dbvolume-dev:
  pgadminvolume-dev:
