version: "3"
services:
  shopping-backend:
    image: nemmtor/shopping-backend
    ports:
      - "4000:4000"
    depends_on:
      - shopping-db
    restart: always

  shopping-frontend:
    image: nemmtor/shopping-frontend
    ports:
      - "5000:5000"
    depends_on:
      - shopping-backend
    restart: always

  shopping-db:
    image: postgres
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbvolume:/var/lib/postgresql/data

  shopping-pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5433:80"
    volumes:
      - pgadminvolume:/var/lib/pgadmin

volumes:
  dbvolume:
  pgadminvolume:
