version: "3"
services:
  shopping-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "4000:4000"
    container_name: shopping-backend
    depends_on:
      - shopping-db
    restart: always

  shopping-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5000:5000"
    container_name: shopping-frontend
    depends_on:
      - shopping-backend
    restart: always

  shopping-db:
    image: postgres
    container_name: shopping-db
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbvolume:/var/lib/postgresql/data

volumes:
  dbvolume:
