openapi: 3.0.0

info:
  title: Shopping List Api
  version: 1.0.0

servers:
  - url: http://localhost:4000
    description: local dev

tags:
  - name: User API

components:
  schemas:
    AuthBody:
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

paths:
  /user/register:
    post:
      summary: Registers user
      tags: [ User API ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthBody'
      responses:
        200:
          description: Registered
        409:
          description: Username already taken
        422:
          description: Invalid body
  /user/login:
    post:
      summary: Login user
      tags: [ User API ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthBody'
      responses:
        200:
          description: Logged in, returns auth token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        401:
          description: Login failed due to wrong username or password
